version: 0.1
   
phases:
  install:
    commands:
      - ls
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://alexbilbiecom
      - ls
